"""Parent camp category taxonomy for gap-fill Phase C."""

GAP_CATEGORIES: tuple[str, ...] = (
    "sports",
    "stem",
    "arts",
    "music",
    "theater",
    "nature",
    "special_needs",
    "overnight",
    "preschool",
    "academic",
    "language",
    "cooking",
    "chess",
    "dance",
    "swim",
    "tennis",
    "soccer",
    "basketball",
    "robotics",
    "coding",
    "adventure",
    "leadership",
    "faith",
    "multi_sport",
)

GAP_SEARCH_TEMPLATES: dict[str, str] = {
    "sports": "{town} MA youth summer sports camp registration",
    "stem": "{town} MA kids STEM summer camp",
    "arts": "{town} MA summer art camp children",
    "music": "{town} MA summer music camp kids",
    "theater": "{town} MA summer theater camp youth",
    "nature": "{town} MA nature outdoor summer camp kids",
    "special_needs": "{town} MA special needs summer camp adaptive",
    "overnight": "{town} MA overnight summer camp",
    "preschool": "{town} MA preschool summer camp",
    "academic": "{town} MA academic enrichment summer camp",
    "language": "{town} MA language immersion summer camp kids",
    "cooking": "{town} MA kids cooking summer camp",
    "chess": "{town} MA chess summer camp kids",
    "dance": "{town} MA dance summer camp youth",
    "swim": "{town} MA swim summer camp lessons kids",
    "tennis": "{town} MA tennis summer camp youth",
    "soccer": "{town} MA soccer summer camp kids",
    "basketball": "{town} MA basketball summer camp youth",
    "robotics": "{town} MA robotics summer camp kids",
    "coding": "{town} MA coding summer camp children",
    "adventure": "{town} MA adventure summer day camp",
    "leadership": "{town} MA teen leadership summer program",
    "faith": "{town} MA faith based summer camp kids",
    "multi_sport": "{town} MA multi sport summer camp kids",
}
